name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: compile and test
      id: compile-and-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: compile and test
        setup-command: make tester
        command: "./tester"
        timeout: 6
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        COMPILE-AND-TEST_RESULTS: "${{steps.compile-and-test.outputs.result}}"
      with:
        runners: compile-and-test
